var defaultItemGrid = [
    [
        "Bow",
        "Hookshot",
        "Hammer",
        "Bombs",
        "Scale",
        "Glove",
    ],
    [
        "KokiriSword",
        "BiggoronSword",
        "MirrorShield",
        "ZoraTunic",
        "GoronTunic",
        "IronBoots",
        "HoverBoots",
    ],
    [
        "Dins",
        "Farores",
        "Nayrus",
        "Magic",
        "Fire",
        "Ice",
        "Light",
    ],
    [
        "Slingshot",
        "Boomerang",
        "Lens",
        "Bottle",
        "ZoraLetter",
        "Wallet",
        "Skulltula",
    ],
    [
        "ZeldasLullaby",
        "EponasSong",
        "SunsSong",
        "SariasSong",
        "SongofTime",
        "SongofStorms",
    ],
    [
        "MinuetofForest",
        "BoleroofFire",
        "SerenadeofWater",
        "NocturneofShadow",
        "RequiemofSpirit",
        "PreludeofLight",
    ],
    [
        "ForestMedallion",
        "FireMedallion",
        "WaterMedallion",
        "ShadowMedallion",
        "SpiritMedallion",
        "LightMedallion",
    ],
    [
        "blank",
        "blank",
        "KokiriEmerald",
        "GoronRuby",
        "ZoraSapphire",
        "blank",
        "blank",
    ]
]


var baseItems = {
    Bow: 0,
    Hookshot: 0,
    Hammer: false,
    Slingshot: 0,
    Boomerang: false,
    Bombs: 0,
    Lens: false,
    Dins: false,
    Farores: false,
    Nayrus: false,
    Fire: false,
    Ice: false,
    Light: false,
    Ocarina: 1,
    Bottle: 0,
    Wallet: 0,
    Skulltula: 0,

    KokiriSword: false,
    BiggoronSword: false,
    MirrorShield: false,
    GoronTunic: false,
    ZoraTunic: false,
    IronBoots: false,
    HoverBoots: false,
    Glove: 0,
    Scale: 0,
    StoneofAgony: false,
    Magic: 0,
    ZoraLetter: false,

    ZeldasLullaby: false,
    EponasSong: false,
    SunsSong: false,
    SariasSong: false,
    SongofTime: false,
    SongofStorms: false,
    MinuetofForest: false,
    PreludeofLight: false,
    BoleroofFire: false,
    SerenadeofWater: false,
    NocturneofShadow: false,
    RequiemofSpirit: false,

    KokiriEmerald: false,
    GoronRuby: false,
    ZoraSapphire: false,
    ForestMedallion: false,
    FireMedallion: false,
    WaterMedallion: false,
    SpiritMedallion: false,
    ShadowMedallion: false,
    LightMedallion: false,

    blank: false,
};

var itemsMin = {
    Bow: 0,
    Slingshot: 0,
    Bombs: 0,
    Hookshot: 0,
    Ocarina: 1,
    Bottle: 0,
    Glove: 0,
    Scale: 0,
    Magic: 0,
    Wallet: 0,
    Skulltula: 0,
};

var itemsMax = {
    Bow: 3,
    Slingshot: 3,
    Bombs: 3,
    Hookshot: 2,
    Ocarina: 2,
    Bottle: 4,
    Glove: 3,
    Scale: 2,
    Magic: 2,
    Wallet: 2,
    Skulltula: 5,
};

var progressiveItemCanonicalNames = {
    Bow: ["Bow", "Bigger Quiver", "Biggest Quiver"],
    Slingshot: ["Slingshot", "Bigger Seed Bag", "Biggest Seed Bag"],
    Bombs: ["Bombs", "Bigger Bomb Bag", "Biggest Bomb Bag"],
    Hookshot: ["Hookshot", "Longshot"],
    Ocarina: ["Fairy Ocarina", "Ocarina of Time"],
    Bottle: ["Bottle", "Bottle", "Bottle", "Bottle"],
    Glove: ["Goron Bracelet", "Silver Gauntlets", "Golden Gauntlets"],
    Scale: ["Silver Scale", "Gold Scale"],
    Magic: ["Magic Meter", "Double Magic Meter"],
    Wallet: ["Adult's Wallet", "Giant's Wallet"],
    Skulltula: ["10 Skulls", "20 Skulls", "30 Skulls", "40 Skulls", "50 Skulls"]
};

var coreItems = ["Bow", "Bombs", "Boomerang", "Hookshot", "Glove", "Magic", "MirrorShield", "IronBoots", "HoverBoots", "Hammer", "ZoraLetter", "Dins", "Light", "Farores"];
var songs = [
    "ZeldasLullaby",
    "EponasSong",
    "SunsSong",
    "SariasSong",
    "SongofTime",
    "SongofStorms",
    "MinuetofForest",
    "PreludeofLight",
    "BoleroofFire",
    "SerenadeofWater",
    "NocturneofShadow",
    "RequiemofSpirit"];

var items = Object.assign(baseItems);
